# Shoutout to : Isaac J. Lee (GitHub: @ijlee2)
#   - https://crunchingnumbers.live/2020/03/17/ci-with-github-actions-for-ember-apps/
#   - https://crunchingnumbers.live/2020/08/31/ci-with-github-actions-for-ember-apps-part-2/
#
name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  NODE_VERSION: 14

jobs:
  build-app:
    name: Build app for testing
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - name: Check out a copy of the repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache npm cache and node_modules
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-${{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-${{ env.NODE_VERSION }}-

      - name: Install dependencies
        run: npm install
        if: steps.cache-dependencies.outputs.cache-hit != 'true'

      - name: Build app
        run: npm run build

      - name: Upload app
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist


  lint:
    name: Lint files and dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - name: Check out a copy of the repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache npm cache and node_modules
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-${{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-${{ env.NODE_VERSION }}-

      - name: Install dependencies
        run: npm install
        if: steps.cache-dependencies.outputs.cache-hit != 'true'

      - name: Lint
        run: npm run lint


  test-app:
    name: Test app
    needs: [build-app]
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - name: Check out a copy of the repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache npm cache and node_modules
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-${{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-${{ env.NODE_VERSION }}-

      - name: Install dependencies
        run: npm install
        if: steps.cache-dependencies.outputs.cache-hit != 'true'

      - name: Download app
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: Test
        run: npm run test:ember-compatibility ${{ matrix.scenario }}


  test-compatibility:
    name: Test compatibility
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario:
          - 'ember-lts-3.16'
          - 'ember-lts-3.20'
          - 'ember-release'
          - 'ember-beta'
          - 'ember-canary'
    timeout-minutes: 7
    steps:
      - name: Check out a copy of the repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache npm cache and node_modules
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-${{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-${{ env.NODE_VERSION }}-

      - name: Install dependencies
        run: npm install
        if: steps.cache-dependencies.outputs.cache-hit != 'true'

      - name: Download app
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      # Test compatibility with ember-try
      - name: Test
        run: npm run test:ember-compatibility ${{ matrix.scenario }}
